name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: ':rocket: Major Updates'
    labels:
      - 'feature'
      - 'enhancement'
      - 'Major'
      - 'major'
      - 'Feature'
  - title: ':penguin: Other Updates'
    labels:
      - 'Update'
      - 'Update' 
  - title: ':turtle: Minor Updates'
    labels:
      - 'minor'
      - 'Minor'
  - title: ':bug: Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'BugFix'
      - 'BugPatch'
  - title: ':robot: Maintenance'
    labels: 
      - 'chore'
      - 'Chore'
      - 'Dependencies'
      - 'dependencies'
      - 'Dependency'
      - 'dependency'
  - title: ':arrow_up: Dependencies Updates'
    labels: [dependencies]
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES
